### ISSUE TITLE
type argument 'T' violates the constraint of type parameter 'T'.

### ISSUE THREAD

**Issue by Wautvda** [vescon/MethodBoundaryAspect.Fody#29]
With the latest release I have the following exception in the most basic application:

> type argument 'T' violates the constraint of type parameter 'T'.

Testproject where this fails can be found at https://github.com/Wautvda/TestProjectMethodBoundryAspect
The only thing it does is serialize a class to XML and the serialisation methods are intercepted by the MethodBoundryAspect and print some testcode to console.

If the Attribute is removed everything runs fine. Haven't found the real cause yet.

Fody v3.03
MethodBoundryAspect v1.0.41

**Comment by marcells** [comment]
@Ralf1108 thinks it is because of the generic constraint ` where T : class`. It could, be that we don't copy the constraints when the method is weaved.

Do you think you could create a test an fix that issue? You can find the place in the code [here](https://github.com/vescon/MethodBoundaryAspect.Fody/blob/30a1f76da8cd8320d96088fce6fc44a437566595/MethodBoundaryAspect.Fody/MethodWeaver.cs#L251).

**Comment by Wautvda** [comment]
Yeah could be. I'm trying to log method returntypes and stumbled on the same problem. Sometimes it isn't possible to get the Generic type through reflection. 
I'll give the fix and test a go and make a PR when I found something!

**Comment by marcells** [comment]
Thank you very much!

**Comment by Wautvda** [comment]
Almost there, just got a problem testing with interface and implementedclass (for example TestClass) as parameter.

Struct, class and new() run fine.

**Comment by Wautvda** [comment]
Fix in PR #30

**Comment by Ralf1108** [comment]
fixed with PR #30
