### ISSUE TITLE
Generic Types: Method not fully instantiated

### ISSUE THREAD

**Issue by bergziege** [vescon/MethodBoundaryAspect.Fody#33]
Maybe this follows on #12 

I have following .net core class

    public class GenericHibernateDao<TEntity, TId> : IGenericHibernateDao<TEntity, TId> where TEntity : Entity{
        [FodyDummy]
        public IList<TEntity> GetAll() {
            return CurrentSession.CreateCriteria(typeof(TEntity)).List<TEntity>();
        }
    }

Error that I get during execution/test run (not on compile):

    System.InvalidOperationException : Could not execute the method because either the method itself or the containing type is not fully instantiated.

The decomlied source looks like this:

    [DebuggerStepThrough]
    [Transaction(true, new Type[] {})]
    public IList<TEntity> GetAll()
    {
        object[] objArray = new object[0];
        MethodExecutionArgs args = new MethodExecutionArgs();
        args.set_Arguments(objArray);
        MethodBase currentMethod = MethodBase.GetCurrentMethod();
        args.set_Method(currentMethod);
        object obj = (object) this;
        args.set_Instance(obj);
        TransactionAttribute transactionAttribute = new TransactionAttribute(true, new Type[0]);
        transactionAttribute.OnEntry(args);
        GenericHibernateDao<TEntity, TId> genericHibernateDao = this;
        IList<TEntity> all;
        try
        {
            all = ((GenericHibernateDao<,>) genericHibernateDao).$_executor_GetAll();
        }
        catch (Exception ex)
        {
            Exception exception = ex;
            args.set_Exception(exception);
            transactionAttribute.OnException(args);
            throw ex;
        }
        args.set_ReturnValue((object) all);
        transactionAttribute.OnExit(args);
        return all;
    }

What I think that could trigger the Exception is the line `all = ((GenericHibernateDao<,>) genericHibernateDao).$_executor_GetAll();` where the generic types are missing. Two lines above they are correctly set `GenericHibernateDao<TEntity, TId> genericHibernateDao = this;`

Would be nice if you could have a look at this ;-)
Thanks,
bergziege

**Comment by Ralf1108** [comment]
yes this looks like a bug and you analysis seems to be correct

**Comment by keith-anders** [comment]
The issue is that when `MethodDefinition` is passed to a `Call` or `Callvirt` instruction, it tries to call it on the `TypeDefinition` of the declaring type, even if it has a proper `TypeReference`. Since `TypeDefinition` loses all the generic argument info and the cloned version of the unweaved method was being passed in as a `MethodDefinition`, it was trying to call the method on the open generic instead of the resolved one. The solution is to make sure you give it a `MethodReference` instead of a `MethodDefinition` (which shouldn't matter since `MethodDefinition` derives from `MethodReference`, but it does seem to matter). See the PR I just submitted.
