### ISSUE TITLE
get parameter's name of method

### ISSUE THREAD

**Issue by minhhungit** [vescon/MethodBoundaryAspect.Fody#63]
Hi team, 
Currently it looks we just have values of parameters, any way that we can get parameter name

Thank you

**Comment by Ralf1108** [comment]
Hi,
Please check the provided MethodExecutionArgs in each OnXXX method. There you have the property Method which can be casted to MethodInfo. 
This is the same object you know from .Net reflection which contains every info about the weaved method.

Please check if it is really a MethodInfo because it could also be a ConstructorInfo.

Check
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodbase?view=netframework-4.7.2

**Comment by minhhungit** [comment]
@Ralf1108 thanks, but I worry that using reflection will reduce performance

**Comment by Ralf1108** [comment]
The method info will be currently provided even if you don't use it.
For performance consideration you have to Benchmark your code.
If it is still too slow provide optimize PR or use commercial PostSharp
