### ISSUE TITLE
In the OnException method get the value from the body of the main method?

### ISSUE THREAD

**Issue by itoop2019** [vescon/MethodBoundaryAspect.Fody#64]
Hi, developers!

Tell me, please, is there a possibility in the OnException method to get the value from the body of the main method?

For example, I perform some method, the state of my objects in the method changes, and there is an exception. I need to log the state of my objects at the time of the error.

**Comment by Ralf1108** [comment]
With "get the value from the body of the main method" you mean local variables from the method?
This is not possible because would live on the stack. I could access them somehow via low level stack analyzing but it is not supported in any way.

In the aspect you can only access the arguments with which the method was invoked including the object reference if it is an instance method.

Please check the MethodExecutionArgs argument of the OnException method:
[MethodExecutionArgs ](https://github.com/vescon/MethodBoundaryAspect.Fody/blob/master/src/MethodBoundaryAspect/Attributes/MethodExecutionArgs.cs)

There is a property for the this reference: Instance
And a property for the provided arguments: Arguments


So... if you use an object as a method argument this is accessible in the aspect. And you should be able to observe all changes done to this object in your method until the exception occurs.

**Comment by itoop2019** [comment]
Fine! Thank you very much!

This option is not even bad.
